### ISSUE TITLE
Please expand to all colors

### ISSUE THREAD

**Issue by henricook** [patrickmineault/ismyblue#1]
This is freaking great, can you please give me a series of tests so I can produce a list of colors and my skews?

This might finally explain why my wife's navy blue dress always looks black to me

**Comment by itsbapic** [comment]
Hey @henricook! I made a fork over the past couple days and just launched the version today that has all colors! Feel free to check it out. https://github.com/itsbapic/ismycolor

**Comment by henricook** [comment]
Amazing work!
