### ISSUE TITLE
Submit doesn't handle timestamp formatting locale-independently

### ISSUE THREAD

**Issue by fogti** [patrickmineault/ismyblue#2]
I've found a bug in the result submission
> invalid input syntax for type timestamp with time zone: "4/9/2024, 12:11:29 μ.μ."

It doesn't handle timestamp formatting independently of locale, and then complains about its syntax.

**Comment by patrickmineault** [comment]
Fixed by https://github.com/patrickmineault/ismyblue/commit/bac53166ef90981d40f8647a2339e7f757e67063
